<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helpers\**" />
    <EmbeddedResource Remove="Helpers\**" />
    <None Remove="Helpers\**" />
    <Page Remove="Helpers\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\icone.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>

	<PropertyGroup>
		<ApplicationIcon>Resources\icone.ico</ApplicationIcon>
	</PropertyGroup>

</Project>
