<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\BaseFlow.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\BaseFlow.ico" />
  </ItemGroup>


	<ItemGroup>
		<None Update="Data\cargos.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Update="Manual\Manual_BaseFlow.pdf">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
	
	
	
	

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Helpers\" />
  </ItemGroup>

</Project>
