<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Icone\editar.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Icone\editar.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.15" />
    <PackageReference Include="PdfSharpCore" Version="1.3.67" />
  </ItemGroup>

</Project>
